[package]
name = "spdlog-opentelemetry"
version = "0.1.0"
edition = "2024"
description = "Sends logs to OpenTelemetry, based on spdlog-rs"
repository = "https://github.com/SpriteOvO/spdlog-opentelemetry"
license = "MIT OR Apache-2.0"
keywords = ["spdlog", "log", "logging", "opentelemetry"]
categories = ["development-tools::debugging"]

[package.metadata.docs.rs]
all-features = true
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]

[lints.clippy]
must_use_candidate = "warn"

[dependencies]
opentelemetry = { version = "0.31.0", features = ["logs"] }
spdlog-rs = "0.5.2"
thiserror = "2.0.17"
value-bag = { version = "1.11.1", features = ["owned", "inline-i128"] }

[dev-dependencies]
opentelemetry-otlp = { version = "0.31.0", features = ["grpc-tonic", "logs"] }
opentelemetry_sdk = "0.31.0"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }

[[example]]
name = "usage"
doc-scrape-examples = true
